### ISSUE TITLE
Multilanguage plans ?

### ISSUE THREAD

**Issue by mariantanase** [thexmanxyz/Cookie-Consent-Neo-Gantry#2]
How can this atom be translated into Italian (or other languages) ?

**Comment by thexmanxyz** [comment]
@mariantanase backend or frontend?

**Comment by mariantanase** [comment]
both :)

**Comment by thexmanxyz** [comment]
@mariantanase For backend translation see also [Gantry Issue #84](https://github.com/gantry/gantry5/issues/84). This is planned but not implemented as far as i understand. For frontend translation I can offer a basic translation option for different languages if you sent me an mail with the translation for the buttons and banner (i don't speak Italian => only a few words at max) I will include this with next release. Please take the email included in the header of the twig and yaml file. Thanks and regards

**Comment by thexmanxyz** [comment]
@mariantanase the backend translation is possible but has to be done manually in the yaml if you do this you can also send the translated yaml back to me and i will include it in the next release or simply create a pull request with an additional yaml

**Comment by mariantanase** [comment]
ok, I'll do that.
Should it be renamed ? (e.g. cookie-consent-neo-it.yaml)

**Comment by thexmanxyz** [comment]
@mariantanase thanks! that sounds good :). for the frontend translation please send me a mail because i have to change some things in the atom to properly load translated strings

**Comment by thexmanxyz** [comment]
@mariantanase As soon as I have the frontend translation I will create default selection for DE, EN and IT

**Comment by mariantanase** [comment]
I sent you the file.
You have two emails :)

**Comment by thexmanxyz** [comment]
@mariantanase German and Italian translation now available with v1.3.0. J3 Plugin Files also included in the latest release.

**Comment by thexmanxyz** [comment]
@mariantanase Full multi language support included with https://github.com/thexmanxyz/Cookie-Consent-Neo-Gantry/commit/b3b1dce0a4ed1a000c096eec5483c4e1c5941439. Latest version which includes the new functionality available now: [v1.5.0](https://github.com/thexmanxyz/Cookie-Consent-Neo-Gantry/releases/tag/v1.5.0)
