### ISSUE TITLE
Only for Hydrogen & Helium?

### ISSUE THREAD

**Issue by N8Solutions** [thexmanxyz/Cookie-Consent-Neo-Gantry#4]
I'm curious to know why there are separate particles for Hydrogen & Helium?
Is there some specific css styling that has been done to work with those templates?

**Comment by thexmanxyz** [comment]
@N8Solutions No, it has todo with the install path / directory. 

- **Hydrogen:** /templates/g5_hydrogen/custom
- **Helium:** /template/g5_helium/custom

Sadly Gantry has no install system so we have to stick with the Joomla Plugin system and there's no way to determine the current or active installed Gantry theme (there can also be two installed at once). So this is the reason to provide separate packages. But maybe there is a possibility in the Joomla install system to check whether the folder is there or not but IDK if there is a way to check that.

For more info take a look in the xml files of the plugins :). If there is a way todo that I wil take that into account with the next release.

**Comment by thexmanxyz** [comment]
@N8Solutions Possibly this can be solved with a installer script?! Just throwing in as an idea. See also https://docs.joomla.org/Manifest_files . For the moment I took the easiest way and that's simply generating multiple packages :)

**Comment by N8Solutions** [comment]
So we can still do a manual install instead of the automatic. This way it could be applied to other themes, correct?

**Comment by thexmanxyz** [comment]
@N8Solutions Yes you can always chose the manual installation and it's currently the only way for none helium/hydrogen themes. However I will think about a more generic installer script which simply checks on folder existance and place it to every available gantry template. That would be way better solution. Thanks for pointing that out I will check that.

**Comment by thexmanxyz** [comment]
@N8Solutions There would be a nice and generic approach. However this would mean that the particles have to be placed under `media/gantry5/engines/nucleus/particles` which is the core folder of gantry for placing atoms and particles. This would make them available whatever template is installed! any thoughts on this idea?! this would allow me to provide just one package for all gantry based joomla templates :)

**Comment by thexmanxyz** [comment]
@N8Solutions As of [v1.5.1](https://github.com/thexmanxyz/Cookie-Consent-Neo-Gantry/releases/tag/v1.5.1) which I released a few minutes ago, we now have finally a working solution which also takes care of global resources (`*.js, *.css`).

You can now install the Plugin a/o:
 * globally (all templates can use the Atom)
 * per template (only the actual template can use the Atom)

So you are able to install it globally as well as for a template (e.g. Helium) independently. However, template files always override global installed ones, so be aware. However coexistence incl. (de)installation does work without issue between global and template installations.

Global installation path is: `/media/gantry5/engines/nucleus`

All my other Particles will soon also receive an update for global plugin installation, thanks to the build automatization script I wrote [Package Builder Gantry](https://github.com/thexmanxyz/Package-Builder-Gantry)

/closed
