### ISSUE TITLE
Translation does not work properly

### ISSUE THREAD

**Issue by Attack44** [thexmanxyz/Cookie-Consent-Neo-Gantry#6]
I have the problem that the translation of the buttons of accept and decline  do not work. Depending on whether opt-in or opt-out is activated.

opt-in is active:
![opt-in](https://user-images.githubusercontent.com/19206966/69339752-604bcf80-0c66-11ea-8601-02a5c4c35ec1.PNG)

opt-out is active:
![opt-out](https://user-images.githubusercontent.com/19206966/69339753-604bcf80-0c66-11ea-96fa-d99c80055783.PNG)

![settings](https://user-images.githubusercontent.com/19206966/69339754-604bcf80-0c66-11ea-838b-d42cc6fc7a90.PNG)

**Comment by thexmanxyz** [comment]
@Attack44 First and foremost, thanks for reporting the issue I will get on it in the next minutes, report back a/o release a fix for the problem. It might be a bug within the Cookie Consent library but I will check and provide more information.

**Comment by thexmanxyz** [comment]
@Attack44 You were right there was a bug in the creation of the JS parameters for the Cookie Consent JS API. Either the `accept` or the `deny` string were translated but not both simultaneously. With the already available release [v1.5.10](https://github.com/thexmanxyz/Cookie-Consent-Neo-Gantry/releases/tag/v1.5.10) the problem should be fixed. Thanks for reporting the issue I completely missed that case. If you notice any further issues don't hesitate to open another issue. 

/closed
